development:
  adapter: mysql2
  database: rvm1cap3
  pool: 5
  timeout: 5000
  username: root
  password:
  
staging: 
  adapter: mysql2
  encoding: utf8
  database: rvm1cap3
  host: 127.0.0.1
  username: root
  password: 

  